# Generated by Django 4.0.1 on 2023-10-17 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=255)),
                ('visfatin_number', models.FloatField()),
                ('MDA_number', models.FloatField()),
                ('FMD_number', models.CharField(max_length=15)),
                ('patient_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientdata.patient')),
            ],
        ),
    ]
